// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx05KfSmBwKb4aeW--Ngpx84US2ZvtQPw',
    appId: '1:533740996041:web:54bb3cb0992d1ef257d418',
    messagingSenderId: '533740996041',
    projectId: 'jobfinderapp-c5a31',
    authDomain: 'jobfinderapp-c5a31.firebaseapp.com',
    storageBucket: 'jobfinderapp-c5a31.appspot.com',
    measurementId: 'G-C00V182XQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Y9ZCShIYcrfHt_mcZSeyps9TP2WkVdk',
    appId: '1:533740996041:android:1a2cb70468ea5f9457d418',
    messagingSenderId: '533740996041',
    projectId: 'jobfinderapp-c5a31',
    storageBucket: 'jobfinderapp-c5a31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDIV4dADb9i1MNPZYvAaCXt_GQh1kCVQ',
    appId: '1:533740996041:ios:365e92146710275557d418',
    messagingSenderId: '533740996041',
    projectId: 'jobfinderapp-c5a31',
    storageBucket: 'jobfinderapp-c5a31.appspot.com',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBDIV4dADb9i1MNPZYvAaCXt_GQh1kCVQ',
    appId: '1:533740996041:ios:b5c595333d25edab57d418',
    messagingSenderId: '533740996041',
    projectId: 'jobfinderapp-c5a31',
    storageBucket: 'jobfinderapp-c5a31.appspot.com',
    iosBundleId: 'com.example.jobFinderApp.RunnerTests',
  );
}
